// Clase para test de CRUD gestion pacientes
package Vista;

//llamada a las clase conexion
import Conexion.ConectarDB;
import javax.swing.JOptionPane;

// llamada al paquete POO y su clase Paciente contendora de componentes oriendatos a objetos
import POO.Paciente;


public class Gestion_CRUD_Paciente extends javax.swing.JFrame {
    //realizar un objeto conexion para el llamado permanente de sus elementos
    ConectarDB conBD = new ConectarDB();
    Paciente objPaciente = new Paciente(); // generar "N" usuarios

    
    public Gestion_CRUD_Paciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreHosp = new javax.swing.JLabel();
        lblLogoHosp = new javax.swing.JLabel();
        panAltaPacientes = new javax.swing.JPanel();
        lblNombres = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblCURP = new javax.swing.JLabel();
        lblDiasHosp = new javax.swing.JLabel();
        lblCostoDia = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtCURP = new javax.swing.JTextField();
        txtDiasHosp = new javax.swing.JTextField();
        txtCostoDia = new javax.swing.JTextField();
        btnRegistroPaciente = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombreHosp.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblNombreHosp.setText("Hospital Privado Ramírez S.A de C.V");

        lblLogoHosp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Hospital Logo.png"))); // NOI18N

        panAltaPacientes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alta de Paciente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 204))); // NOI18N

        lblNombres.setText("Nombre:");

        lblApellidos.setText("Apellidos:");

        lblCURP.setText("CURP:");

        lblDiasHosp.setText("Días de Hospitalización:");

        lblCostoDia.setText("Cobro por Día $:");

        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });

        txtDiasHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiasHospActionPerformed(evt);
            }
        });

        txtCostoDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoDiaActionPerformed(evt);
            }
        });

        btnRegistroPaciente.setText("Registrar Paciente");
        btnRegistroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroPacienteActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panAltaPacientesLayout = new javax.swing.GroupLayout(panAltaPacientes);
        panAltaPacientes.setLayout(panAltaPacientesLayout);
        panAltaPacientesLayout.setHorizontalGroup(
            panAltaPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAltaPacientesLayout.createSequentialGroup()
                .addGroup(panAltaPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAltaPacientesLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(panAltaPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCostoDia)
                            .addComponent(lblNombres)
                            .addComponent(lblApellidos)
                            .addComponent(lblCURP)))
                    .addGroup(panAltaPacientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDiasHosp)))
                .addGap(51, 51, 51)
                .addGroup(panAltaPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDiasHosp)
                    .addComponent(txtNombres)
                    .addComponent(txtApellidos)
                    .addComponent(txtCURP)
                    .addComponent(txtCostoDia, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panAltaPacientesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnRegistroPaciente)
                .addGap(52, 52, 52)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(47, 47, 47))
        );
        panAltaPacientesLayout.setVerticalGroup(
            panAltaPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAltaPacientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panAltaPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panAltaPacientesLayout.createSequentialGroup()
                        .addGroup(panAltaPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombres)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(panAltaPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellidos)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(lblCURP))
                    .addComponent(txtCURP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panAltaPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiasHosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiasHosp))
                .addGap(34, 34, 34)
                .addGroup(panAltaPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCostoDia)
                    .addComponent(txtCostoDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(panAltaPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistroPaciente)
                    .addComponent(btnLimpiar)
                    .addComponent(btnSalir))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblLogoHosp, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreHosp)
                .addContainerGap(205, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panAltaPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogoHosp, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblNombreHosp)))
                .addGap(18, 18, 18)
                .addComponent(panAltaPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtDiasHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiasHospActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiasHospActionPerformed

    private void btnRegistroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroPacienteActionPerformed
    //llamada a la conexión de BD
    conBD.conectarBase ();

    //capturar los datos desde el formulario a el objeto
    objPaciente.setRgNombre(txtNombres.getText());
    objPaciente.setRgApellidos(txtApellidos.getText());
    objPaciente.setRgCURP(txtCURP.getText());
    objPaciente.setRgDiasHosp(Integer.parseInt(txtDiasHosp.getText()));
    objPaciente.setRgCobroDia(Integer.parseInt(txtCostoDia.getText()));

    //insertar un registro hasta base de datos
    String altaPaciente = "INSERT INTO t_pacientes values ('" + objPaciente.getRgCURP() + "', '" + objPaciente.getRgDiasHosp() + "', '" + objPaciente.getRgCobroDia() + "' , '" + objPaciente.getRgNombre() + "' , '" + objPaciente.getRgApellidos() + "') " ;    
       
    try { //trata de realizar y compilar ejecutar
        conBD.stmt.executeUpdate(altaPaciente);
        JOptionPane.showMessageDialog(null,"Exito al ingresar paciante: \n" + objPaciente.getRgNombre() + " " + objPaciente.getRgApellidos());
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error 1 de BD ALTA\n"+ e);
    }
    }//GEN-LAST:event_btnRegistroPacienteActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0); //cierra ventana
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtNombres.setText(null);
        txtApellidos.setText(null);
        txtCURP.setText(null);
        txtDiasHosp.setText(null);
        txtCostoDia.setText(null);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtCostoDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoDiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_CRUD_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_CRUD_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_CRUD_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_CRUD_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_CRUD_Paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistroPaciente;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCURP;
    private javax.swing.JLabel lblCostoDia;
    private javax.swing.JLabel lblDiasHosp;
    private javax.swing.JLabel lblLogoHosp;
    private javax.swing.JLabel lblNombreHosp;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JPanel panAltaPacientes;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCURP;
    private javax.swing.JTextField txtCostoDia;
    private javax.swing.JTextField txtDiasHosp;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
