
package vista;

//llamada a las clase conexion
import conexion.ConectarDB;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

// llamada al paquete POO y su clase Usuario contendora de componentes oriendatos a objetos
import poo.Equipo;


public class Vendedor extends javax.swing.JFrame {
    //Oobjeto conexion para el llamado permanente de sus elementos
    ConectarDB conBD = new ConectarDB();
    Equipo objEquipo = new Equipo(); // generar "N" usuarios
    
    public Vendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panFondo = new javax.swing.JPanel();
        lblBienvenido = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        panRegistro = new javax.swing.JPanel();
        lblRegistroID = new javax.swing.JLabel();
        lblRegistroMarca = new javax.swing.JLabel();
        txtRegistroMarca = new javax.swing.JTextField();
        txtRegistroID = new javax.swing.JTextField();
        lblRegistroModelo = new javax.swing.JLabel();
        lblRegistroPrecio = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtRegistroModelo = new javax.swing.JTextField();
        txtRegistroPrecio = new javax.swing.JTextField();
        panConsulta = new javax.swing.JPanel();
        lblConsultaMarca = new javax.swing.JLabel();
        txtConsultaMarca = new javax.swing.JTextField();
        txtConsultaID = new javax.swing.JTextField();
        lblConsultaModelo = new javax.swing.JLabel();
        lblConsultaPrecio = new javax.swing.JLabel();
        txtConsultaModelo = new javax.swing.JTextField();
        txtConsultaPrecio = new javax.swing.JTextField();
        btnConsulta = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panFondo.setBackground(new java.awt.Color(241, 239, 231));

        lblBienvenido.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        lblBienvenido.setText("¡Bienvenido Vendedor!");

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo 2.png"))); // NOI18N

        panRegistro.setBackground(new java.awt.Color(241, 239, 231));
        panRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro Equipos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 1, 20))); // NOI18N
        panRegistro.setForeground(new java.awt.Color(241, 239, 231));

        lblRegistroID.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        lblRegistroID.setText("ID Equipo:");

        lblRegistroMarca.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        lblRegistroMarca.setText("Marca:");

        txtRegistroMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistroMarcaActionPerformed(evt);
            }
        });

        lblRegistroModelo.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        lblRegistroModelo.setText("Modelo:");

        lblRegistroPrecio.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        lblRegistroPrecio.setText("Precio:");

        jButton1.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtRegistroPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistroPrecioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panRegistroLayout = new javax.swing.GroupLayout(panRegistro);
        panRegistro.setLayout(panRegistroLayout);
        panRegistroLayout.setHorizontalGroup(
            panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRegistroLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRegistroModelo)
                    .addComponent(lblRegistroID)
                    .addComponent(lblRegistroMarca)
                    .addComponent(lblRegistroPrecio))
                .addGap(18, 18, 18)
                .addGroup(panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(txtRegistroID, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegistroMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegistroModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegistroPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        panRegistroLayout.setVerticalGroup(
            panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRegistroLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegistroID)
                    .addComponent(txtRegistroID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegistroMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegistroMarca))
                .addGap(28, 28, 28)
                .addGroup(panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegistroModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegistroModelo))
                .addGap(25, 25, 25)
                .addGroup(panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegistroPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegistroPrecio))
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        panConsulta.setBackground(new java.awt.Color(241, 239, 231));
        panConsulta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta Equipos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 1, 20))); // NOI18N
        panConsulta.setForeground(new java.awt.Color(241, 239, 231));

        lblConsultaMarca.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        lblConsultaMarca.setText("Marca:");

        txtConsultaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultaMarcaActionPerformed(evt);
            }
        });

        txtConsultaID.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        txtConsultaID.setText("Insertar ID Producto");

        lblConsultaModelo.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        lblConsultaModelo.setText("Modelo:");

        lblConsultaPrecio.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        lblConsultaPrecio.setText("Precio:");

        txtConsultaPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultaPrecioActionPerformed(evt);
            }
        });

        btnConsulta.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        btnConsulta.setText("Consultar");
        btnConsulta.setToolTipText("");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panConsultaLayout = new javax.swing.GroupLayout(panConsulta);
        panConsulta.setLayout(panConsultaLayout);
        panConsultaLayout.setHorizontalGroup(
            panConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConsultaLayout.createSequentialGroup()
                .addGroup(panConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panConsultaLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(txtConsultaID, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConsulta))
                    .addGroup(panConsultaLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(panConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblConsultaMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblConsultaPrecio, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(lblConsultaModelo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConsultaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConsultaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConsultaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panConsultaLayout.setVerticalGroup(
            panConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConsultaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConsultaID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(panConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConsultaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConsultaMarca))
                .addGap(28, 28, 28)
                .addGroup(panConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConsultaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConsultaModelo))
                .addGap(25, 25, 25)
                .addGroup(panConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConsultaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConsultaPrecio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalir.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setToolTipText("");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panFondoLayout = new javax.swing.GroupLayout(panFondo);
        panFondo.setLayout(panFondoLayout);
        panFondoLayout.setHorizontalGroup(
            panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addComponent(panRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addComponent(imgLogo)
                        .addGap(150, 150, 150)
                        .addComponent(lblBienvenido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)))
                .addGap(23, 23, 23))
        );
        panFondoLayout.setVerticalGroup(
            panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoLayout.createSequentialGroup()
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblBienvenido))
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgLogo))))
                .addGap(34, 34, 34)
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        panConsulta.getAccessibleContext().setAccessibleName("Consulta Equipos");
        panConsulta.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //llamada a la conexión de BD
        conBD.conectarBase();
        
        //capturar los datos desde el formulario a el objeto
        objEquipo.setIdEquipo(Integer.parseInt(txtRegistroID.getText()));
        objEquipo.setMarca(txtRegistroMarca.getText());
        objEquipo.setModelo(txtRegistroModelo.getText());
        objEquipo.setPrecio(Integer.parseInt(txtRegistroPrecio.getText()));

        //insertar un registro hasta base de datos
        String altaEquipo = "INSERT INTO t_equipo values ('"+objEquipo.getIdEquipo()+"', '"+objEquipo.getMarca()+"', '"+objEquipo.getModelo()+"', '"+objEquipo.getPrecio()+"')";
        
        try { //trata de realizar y compilar ejecutar
            conBD.stmt.executeUpdate(altaEquipo);
            JOptionPane.showMessageDialog(null,"Exito al ingresar modelo: \n" + objEquipo.getModelo());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error 1 de BD ALTA\n"+ e);
        }
        
        txtRegistroID.setText(null);
        txtRegistroMarca.setText(null);
        txtRegistroModelo.setText(null);
        txtRegistroPrecio.setText(null);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtRegistroMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroMarcaActionPerformed

    private void txtRegistroPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroPrecioActionPerformed

    private void txtConsultaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultaMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultaMarcaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);//cierra ventaana
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtConsultaPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultaPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultaPrecioActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        //codigo buscar
        try {//estructura de control de tratamiento de errores
            conBD.conectarBase(); //llamada a la conexion de base de datos
            
            int idEquipoBuscar = Integer.parseInt(this.txtConsultaID.getText());
            
            //instruccion para buscar usuario
            conBD.rs = conBD.stmt.executeQuery("SELECT * FROM t_equipo where idEquipo='"+ idEquipoBuscar +"'");
            JOptionPane.showMessageDialog(null, "Buscando Equipo...");
            if (conBD.rs.next()==true) {
                this.txtConsultaID.setText(conBD.rs.getString("idEquipo"));
                this.txtConsultaMarca.setText(conBD.rs.getString("marca"));
                this.txtConsultaModelo.setText(conBD.rs.getString("modelo"));
                this.txtConsultaPrecio.setText(conBD.rs.getString("precio"));
            } else {
                 JOptionPane.showMessageDialog(null, "Error no existe ese ID de Equipo\nVerifica");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error de BD en busqueda de Usuario"+ e);
        }
    }//GEN-LAST:event_btnConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblConsultaMarca;
    private javax.swing.JLabel lblConsultaModelo;
    private javax.swing.JLabel lblConsultaPrecio;
    private javax.swing.JLabel lblRegistroID;
    private javax.swing.JLabel lblRegistroMarca;
    private javax.swing.JLabel lblRegistroModelo;
    private javax.swing.JLabel lblRegistroPrecio;
    private javax.swing.JPanel panConsulta;
    private javax.swing.JPanel panFondo;
    private javax.swing.JPanel panRegistro;
    private javax.swing.JTextField txtConsultaID;
    private javax.swing.JTextField txtConsultaMarca;
    private javax.swing.JTextField txtConsultaModelo;
    private javax.swing.JTextField txtConsultaPrecio;
    private javax.swing.JTextField txtRegistroID;
    private javax.swing.JTextField txtRegistroMarca;
    private javax.swing.JTextField txtRegistroModelo;
    private javax.swing.JTextField txtRegistroPrecio;
    // End of variables declaration//GEN-END:variables
}
